# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blankCanvas, lens, vector }:

cabal.mkDerivation (self: {
  pname = "sluice";
  version = "0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ blankCanvas lens vector ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
